# Generated by Django 4.2.7 on 2024-04-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signinapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='article',
            name='stock',
        ),
    ]
