# Generated by Django 4.2.7 on 2024-05-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signinapp', '0002_remove_article_description_remove_article_prix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
