# Generated by Django 4.2.7 on 2024-05-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signinapp', '0003_yourmodelname_delete_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModelName',
            new_name='article',
        ),
    ]
