# Generated by Django 4.2.7 on 2024-05-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signinapp', '0004_rename_yourmodelname_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reference',
        ),
    ]
