# Generated by Django 4.2.7 on 2024-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signinapp', '0005_remove_article_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
