# Generated by Django 4.2.7 on 2024-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signinapp', '0006_alter_article_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
